---
#
# We're going to set 2 new variables:
#   - cluster: the name of (first) cluster found for given group
#   - cluster_hosts: list of hosts within this cluster without target host
#

- name: Setting up clusters
  no_log: True
  set_fact:
    cluster: "{{ group_names | select('match', (group | mandatory | regex_escape()) + '/.*') | list | first | default(False) }}"
    cluster_hosts: []

- name: Building host redundancy lists
  no_log: True
  when: cluster != False
  set_fact:
    cluster_hosts: "{{ groups[cluster | mandatory] | reject('match', inventory_hostname) | list | default([]) }}"
